In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot
import matplotlib.pyplot as plt
from sklearn import metrics
%matplotlib inline


train_data=pd.read_csv("C:/Users/hp/Downloads/Train_Data.csv")

In [2]:
train_data.head()

,ID1,Specific ailments,ID2,Food preference,Age,BMI,Smoker?,Living in?,Any heriditary condition?,Follow Diet,Physical activity,Regular sleeping hours,Alcohol consumption,Social interaction,Taking supplements,Mental health management,Illness count last year,Healthy
0,2408,44,2668,DX6,49,20.500470,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
1,25063,39,10363,DX3 DX4,20,26.076580,NO,URBAN,Stable,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1
2,26798,29,132,DX6,1,21.420866,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,31907,27,10499,DX1,30,25.203247,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,26412,9,7963,DX6,40,19.355846,YES,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1

In [3]:
test_data=pd.read_csv("C:/Users/hp/Downloads/Test_Data.csv")

In [4]:
test_data.head()

,ID1,Specific ailments,ID2,Food preference,Age,BMI,Smoker?,Living in?,Any heriditary condition?,Follow Diet,Physical activity,Regular sleeping hours,Alcohol consumption,Social interaction,Taking supplements,Mental health management,Illness count last year
0,28534,2,3306,DX6,38,18.879331,YES,URBAN,Stable,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,7970,5,5573,DX1,46,21.231991,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,22039,37,9305,DX4,11,17.867876,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12332,44,8274,DX5,10,26.886096,NO,RURAL,Stable,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
4,4116,37,4558,DX3 DX4,3,23.362746,NO,RURAL,Stable,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0

In [5]:
train_data.shape

(25920, 18)

In [6]:
test_data.shape

(6480, 17)

In [11]:

train_data.dtypes

ID1                            int64
Specific ailments              int64
ID2                            int64
Food preference               object
Age                            int64
BMI                          float64
Smoker?                       object
Living in?                    object
Any heriditary condition?     object
Follow Diet                  float64
Physical activity            float64
Regular sleeping hours       float64
Alcohol consumption          float64
Social interaction           float64
Taking supplements           float64
Mental health management     float64
Illness count last year      float64
Healthy                        int64
dtype: object

In [13]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
train_data['Food preference']= label_encoder.fit_transform(train_data['Food preference'])
train_data['Smoker?']= label_encoder.fit_transform(train_data['Smoker?'])
train_data['Living in?']= label_encoder.fit_transform(train_data['Living in?'])
train_data['Any heriditary condition?']= label_encoder.fit_transform(train_data['Any heriditary condition?'])

In [14]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
test_data['Food preference']= label_encoder.fit_transform(test_data['Food preference'])
test_data['Smoker?']= label_encoder.fit_transform(test_data['Smoker?'])
test_data['Living in?']= label_encoder.fit_transform(test_data['Living in?'])
test_data['Any heriditary condition?']= label_encoder.fit_transform(test_data['Any heriditary condition?'])

In [15]:
train_data.head()

,ID1,Specific ailments,ID2,Food preference,Age,BMI,Smoker?,Living in?,Any heriditary condition?,Follow Diet,Physical activity,Regular sleeping hours,Alcohol consumption,Social interaction,Taking supplements,Mental health management,Illness count last year,Healthy
0,2408,44,2668,31,49,20.500470,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
1,25063,39,10363,25,20,26.076580,1,1,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1
2,26798,29,132,31,1,21.420866,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,31907,27,10499,0,30,25.203247,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,26412,9,7963,31,40,19.355846,2,0,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1

In [16]:
test_data.head()

,ID1,Specific ailments,ID2,Food preference,Age,BMI,Smoker?,Living in?,Any heriditary condition?,Follow Diet,Physical activity,Regular sleeping hours,Alcohol consumption,Social interaction,Taking supplements,Mental health management,Illness count last year
0,28534,2,3306,31,38,18.879331,2,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,7970,5,5573,0,46,21.231991,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,22039,37,9305,28,11,17.867876,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12332,44,8274,30,10,26.886096,1,0,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
4,4116,37,4558,25,3,23.362746,1,0,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0

In [18]:

train_data.isnull().sum()

ID1                            0
Specific ailments              0
ID2                            0
Food preference                0
Age                            0
BMI                            0
Smoker?                        0
Living in?                     0
Any heriditary condition?      0
Follow Diet                  973
Physical activity            973
Regular sleeping hours       973
Alcohol consumption          973
Social interaction           973
Taking supplements           973
Mental health management     973
Illness count last year      973
Healthy                        0
dtype: int64

In [25]:
train_data['Follow Diet']=train_data['Follow Diet'].fillna(train_data['Follow Diet'].mean())
train_data['Physical activity']=train_data['Physical activity'].fillna(train_data['Physical activity'].mean())
train_data['Regular sleeping hours']=train_data['Regular sleeping hours'].fillna(train_data['Regular sleeping hours'].mean())
train_data['Alcohol consumption']=train_data['Alcohol consumption'].fillna(train_data['Alcohol consumption'].mean())
train_data['Social interaction']=train_data['Social interaction'].fillna(train_data['Social interaction'].mean())
train_data['Taking supplements']=train_data['Taking supplements'].fillna(train_data['Taking supplements'].mean())
train_data['Mental health management']=train_data['Mental health management'].fillna(train_data['Mental health management'].mean())
train_data['Illness count last year']=train_data['Illness count last year'].fillna(train_data['Illness count last year'].mean())

In [26]:
train_data.isnull().sum()

ID1                          0
Specific ailments            0
ID2                          0
Food preference              0
Age                          0
BMI                          0
Smoker?                      0
Living in?                   0
Any heriditary condition?    0
Follow Diet                  0
Physical activity            0
Regular sleeping hours       0
Alcohol consumption          0
Social interaction           0
Taking supplements           0
Mental health management     0
Illness count last year      0
Healthy                      0
dtype: int64

In [27]:
test_data.isnull().sum()

ID1                            0
Specific ailments              0
ID2                            0
Food preference                0
Age                            0
BMI                            0
Smoker?                        0
Living in?                     0
Any heriditary condition?      0
Follow Diet                  262
Physical activity            262
Regular sleeping hours       262
Alcohol consumption          262
Social interaction           262
Taking supplements           262
Mental health management     262
Illness count last year      262
dtype: int64

In [28]:
test_data['Follow Diet']=test_data['Follow Diet'].fillna(test_data['Follow Diet'].mean())
test_data['Physical activity']=test_data['Physical activity'].fillna(test_data['Physical activity'].mean())
test_data['Regular sleeping hours']=test_data['Regular sleeping hours'].fillna(test_data['Regular sleeping hours'].mean())
test_data['Alcohol consumption']=test_data['Alcohol consumption'].fillna(test_data['Alcohol consumption'].mean())
test_data['Social interaction']=test_data['Social interaction'].fillna(test_data['Social interaction'].mean())
test_data['Taking supplements']=test_data['Taking supplements'].fillna(test_data['Taking supplements'].mean())
test_data['Mental health management']=test_data['Mental health management'].fillna(test_data['Mental health management'].mean())
test_data['Illness count last year']=test_data['Illness count last year'].fillna(test_data['Illness count last year'].mean())

In [29]:
test_data.isnull().sum()

ID1                          0
Specific ailments            0
ID2                          0
Food preference              0
Age                          0
BMI                          0
Smoker?                      0
Living in?                   0
Any heriditary condition?    0
Follow Diet                  0
Physical activity            0
Regular sleeping hours       0
Alcohol consumption          0
Social interaction           0
Taking supplements           0
Mental health management     0
Illness count last year      0
dtype: int64

In [32]:
X=train_data.iloc[:,0:17]
y=train_data['Healthy']

In [31]:
X.head()

,ID1,Specific ailments,ID2,Food preference,Age,BMI,Smoker?,Living in?,Any heriditary condition?,Follow Diet,Physical activity,Regular sleeping hours,Alcohol consumption,Social interaction,Taking supplements,Mental health management,Illness count last year
0,2408,44,2668,31,49,20.500470,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,25063,39,10363,25,20,26.076580,1,1,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,26798,29,132,31,1,21.420866,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,31907,27,10499,0,30,25.203247,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,26412,9,7963,31,40,19.355846,2,0,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0

In [33]:
y.head()

0    1
1    1
2    0
3    1
4    1
Name: Healthy, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [35]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [36]:
y_pred=tree_clf.predict(test_data)

In [37]:
y_pred

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [38]:
pred_values = pd.DataFrame(y_pred)
pred_values.to_csv("hackathon_submission_file.csv")